### ISSUE TITLE
Replace the latex documentation with a Markdown one

### ISSUE THREAD

**Issue by lambdasapple** [CMBRDB/libcmbrcc#31]
When using latex, I have to include the compiled PDF file in the repo, which is pretty icky, while github has native support for rendering markdown.

**Comment by Whitegabriella789** [comment]
May I work on this issue?

**Comment by lambdasapple** [comment]
> May I work on this issue?

Definitely

**Comment by Whitegabriella789** [comment]
Would you like me to replace the documentation in the pdf with MarkDown?
